version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - ec2-34-221-153-196.us-west-2.compute.amazonaws.com
          - auth.ec2-34-221-153-196.us-west-2.compute.amazonaws.com
          - ws.ranger.wb.local
          - pma.wb.local
          - eth.wb.local
          - monitor.wb.local
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.wb.local'
      traefik.port: 8080
